### ISSUE TITLE
reading xxx.obj failed (80004005)

### ISSUE THREAD

**Issue by SweetBullet** [Microsoft/UVAtlas#10]
when i use uvatlastool:     "reading xxx.obj failed (80004005)"   what's wrong?

**Comment by walbourn** [comment]
The ``HRESULT`` of ``0x80004005`` is ``E_FAIL`` which is pretty generic. There's a number of places in [WaveFrontReader.h](https://github.com/Microsoft/DirectXMesh/blob/master/Utilities/WaveFrontReader.h) where it can generate that error.

Can you provide the Wavefront OBJ file that is failing for further diagnosis? Otherwise, you could just step into the UVAtlas code in the debugger and see what's happening.

**Comment by walbourn** [comment]
I realized today that there are two likely causes of this error:

1. You are missing the .mtl file
1. The Wavefront OBJ is using negative face index values

I updated the WaveFrontReader.h in [this commit](https://github.com/Microsoft/DirectXMesh/commit/5f39e992625a7a58e23dba8bf428eeaa19cba145) to support the negative values.
