### ISSUE TITLE
Missing return E_NOTIMPL;

### ISSUE THREAD

**Issue by WurmD** [microsoft/UVAtlas#44]
I think here

https://github.com/microsoft/UVAtlas/blob/c138b0e0604f2ac693d5b82d24ad1bbf2ff12949/UVAtlas/isochart/meshapplyisomap.cpp#L241
https://github.com/microsoft/UVAtlas/blob/c138b0e0604f2ac693d5b82d24ad1bbf2ff12949/UVAtlas/isochart/meshapplyisomap.cpp#L269-L271

there may be an

``    else
return E_NOTIMPL;
``
or similar missing.

Is there?

**Comment by walbourn** [comment]
Probably it needs an ``return E_INVALIDARG``. Can you provide an example of the input parameters to the public functions you used to hit this condition?

**Comment by WurmD** [comment]
I didn't hit it. I'm working on the code, and read it, looked off and so posted here.

**Comment by walbourn** [comment]
So the implementation code in UVAtlas is quite old and it's challenging to understand some of the initial engineering decisions.

If you use ``UVATLAS_GEODESIC_FAST`` then it skips calling ``InitOneToAllEngine`` by design, and later in the ``CalculateGeodesicDistanceToVertex`` uses the same test and avoids calling the function that would need that init.

Weird, messy, but it works.
